deploy:

  env:
    FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  needs: playwright

  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - run: flyctl deploy --remote-only